version: "3"
services:
  db:
    image: mysql:5.7
    command:
      - "--default-authentication-plugin=mysql_native_password"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "hanan"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
    # volumes:
    #  - "./mysql/database:/var/lib/mysql"
